apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vproapp

  template:
    metadata:
      labels:
        app: vproapp

    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command:
            - sh
            - -c
            - >
              until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
              do
                echo "Waiting for MySQL...";
                sleep 2;
              done

          resources:
            requests:
              cpu: "100m"

        - name: init-rabbitmq
          image: busybox:1.28
          command:
            - sh
            - -c
            - >
              until nslookup vprormq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
              do
                echo "Waiting for RabbitMQ...";
                sleep 2;
              done

          resources:
            requests:
              cpu: "100m"

      containers:
        - name: vproapp
          image: aroy0509/vprofileapp

          ports:
            - name: vproapp-port
              containerPort: 8080

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
